### PR TITLE
Refresh Intervall for status polling

### PR DESCRIPTION
**Pull request by ansgarschulte**
Added Refresh Intervall for status polling:
the client disconnects in between and user is able to user original Smartphone App now and then, which uses the same telnet port

### CODE REVIEW

**Comment by Jey-Cee** [comment]
Why you are closed this PR, Is it obsolet?

**Comment by ansgarschulte** [comment]
No, but I found a bug and I want to fix it first. I will send a new PR, when it is fixed and working at my home.

**Comment by Jey-Cee** [comment]
Ok. Have you seen the post from Stefan at forum? There is a problem with the shutter detection, would be nice if you can fix it. He has tried the github version with your changes but is still not working.

**Comment by ansgarschulte** [comment]
Havent seen it.... something wrong with my forum notifications. But I will have a look

**Comment by ansgarschulte** [comment]
Habs jetzt ziemlich viel gefixt, was Status (Sop) und reconnect betrifft. Bei mir läuft der produktiv. Werde ich auch weiterhin einsetzen und bei Fehlern patchen

**Comment by ansgarschulte** [comment]
Ok

**Comment by ansgarschulte** [comment]
Ok

**Comment by ansgarschulte** [comment]
hi, will you merge it? Stefan and me uses it daily.

**Pull request merged**
